#!/bin/bash

file=$1

#indentation fixes
sed -i.bak 's/        /\t/g' $file

#simple brace fix
sed -i.bak 's/){/)\n{' $file

#space fixes
sed i.bak 's/[if(,else if(,switch(,case(,for(,while(, return(]/${\1%?}/g' $file
